### ISSUE TITLE
Add ability to run "one shot" commands

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/agent#117]
The idea here is to support running preparatory or maintenance tasks  that need to execute as a command that finishes after a while.
Ideally this should also be done via systemd as some of these commands can run for quite a while (days sometimes) and we do not want them aborted, when the agent crashes or is restarted.

This could be done via the following settings:
```
Type=oneshot
RemainAfterExit=true
```
An example can be seen [here](https://gist.github.com/drmalex07/d006f12914b21198ee43). 

I am unsure if RemainAfterExit is necessary, but this might be required to check the exit code of the command afterwards.

**Comment by siegfriedweber** [comment]
Kubernetes jobs behave as follows:
* The job controller creates a pod with the label `job-name=<name of the job>`.
* If the pod terminates successfully then its `status` contains `phase: Succeeded` and `status/containerStatuses/state/terminated` contains `exitCode: 0` and `reason: Completed`.
* If the pod terminates unsuccessfully then its `status` contains `phase: Failed` and `status/containerStatuses/state/terminated` contains `exitCode: <exit code>` and `reason: Error`.
* The job does not delete the pod so that the result can be inspected.

(The job controller actually does a lot more but that is not relevant here.)

This behavior should be replicated in the agent.

**Comment by lfrancke** [comment]
We have this ticket https://github.com/stackabletech/documentation/issues/28 which talks about designing this feature.
That has been superseded by this one.
Is this a thing/change that needs to be documented? I believe so, right? We should document the Agent behavior.
I'll close the other issue in favor of this one.
